### ISSUE TITLE
Text rearrangement for Dr Rambaud and intercom

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#11]
"You can see an intercom and a bloody corpse of Docteur Rambaud here."

Can be arranged with:

after choosing notable locale objects when player is in airlock:
	if corpse of Docteur Rambaud is in airlock, set the locale priority of corpse of Docteur Rambaud to 9; [this assures Inform looks for the corpse first]

rule for printing a locale paragraph about Docteur Rambaud:
  say "The corpse of Docteur Rambaud lies here next to the/an intercom.";
  now corpse of Docteur Rambaud is mentioned;
  now intercom is mentioned;

I'm not sure how well this works with Vorple, but this is a bit of code that comes in handy for me

**Comment by dhakajack** [comment]
After choosing notable locale objects when player is in sas:
	If the bloody corpse of Docteur Rambaud is in sas, set the locale priority of corpse of Docteur Rambaud to 9. [this assures Inform looks for the corpse first]
	
Rule for printing a locale paragraph about the bloody corpse of Docteur Rambaud when the bloody corpse of Docteur Rambaud is in the sas:
	say "The corpse of Docteur Rambaud lies crumpled on the floor not far from the intercom.";
	now the bloody corpse of Docteur Rambaud is mentioned;
	now the intercom is mentioned.
