### ISSUE TITLE
Game informs you you take the scientist/wolf before eating it/them

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#12]
This is a small thing, but "(taking the scientist/wolf)" before eating just their brains seems impractical, especially since tere is not officially have a "take" command for this game.

If you want to wipe this text for all eating, including stuff you can pick up easily,

procedural rule while eating something: ignore the carrying requirements rule.

For only the scientist and wolf,

procedural rule while eating scientist: ignore the carrying requirements rule.
procedural rule while eating wolf: ignore the carrying requirements rule.

**Comment by dhakajack** [comment]
Are procedural rules still a thing? I got this to work:

Rule for implicitly taking something (called the target) while eating:
	try silently taking the target.

**Comment by andrewschultz** [comment]
I keep forgetting they've been deprecated in later inform builds (I use 6G95). So yeah, use the non deprecated code.
