### ISSUE TITLE
"Talk" reject later on is slightly inaccurate

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#14]
"No one is around. Who are you talking to?" contradicts that the consciousnesses can and have been talking to each other. So it'd be nice to have a conditional statement "You'll discuss things when needed." Or something a lot less dry.

**Comment by dhakajack** [comment]
I think this is fair, should work in all instances, and doesn't come of as snarky:

say "You don't see anyone to talk to.";
