### ISSUE TITLE
PUSH in surgical theater gives generic reject

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#15]
The description has "The table has various straps and contraptions to immobilize animals during surgery. Just next to the table is an anesthesia machine, with knobs and dials, and tubes leading to the ceiling." so maybe the game should say, you don't understand any of this, so best not meddle -- or with Dr Rambaud in the consciousness, you don't have anyone to operate on, so best not meddle.

**Comment by dhakajack** [comment]
Instead of simplePushing when the player is in the Bloc Opératoire:
	if the consciousness of the player is less than 4:
		say "You aren't sure what does what in here and don't want to risk accidently dissecting yourself by poking randomly about[one of]. That would be embarassing[or][stopping].";
	otherwise:
		say "You aren't scrubbed in and all the equipment in here is sterile; you don't want to contaminate the equipment."
