### ISSUE TITLE
random grammar/typo policing

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#17]
"Okay… But that would mean… this could be it. An end the pandemic!"

An end to the pandemic

"The first cases were reported in Cambodia and twenty-four hours later thousands"
The first cases were reported in Cambodia, and twenty-four hours later, thousands

**Comment by andrewschultz** [comment]
"I've got a real hankering for something, I just can't quite put my paw on it." may be a runon, or it may be stylistic.

"No, it wasn't like that. I played with the kids, they fed me, they pet me all day, and I even had my own bed."

pet -> petted

**Comment by dhakajack** [comment]
Typos are my favorite!

I stuck an em-dash after "hankering for something".

I think I actually do say "pet" as a past participle, but I also say "draw" for what you put the spoons and knives in. Corrected.
