### ISSUE TITLE
Lucky and counting to 3

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#19]
I like the joke with Lucky and counting to 3, but there's a small contradiction that's nagging at me more than it should.

"Number one", explains the dog, "we need to explore a bit to, as the slice of brain says, secure the installation. Number two: to search for the missing brain. And number… um, the number that comes after two: we need to escape."
"Amazing! You're a genius, Lucky," says the slice of brain.
>* this is very good -- in another place you are able to count to 3. Would you want to reconcile that with this, maybe with a joke? Or was there a joke and I missed it?

 * * *

"Okay," says Isabelle. "How about we renumber? One: prepare the cure; two: get out of the installation; three: find Lucky's family. Does that work for you?"
"Sure," says Lucky, "that sounds entirely reasonable."
"And it's mathematically correct," adds the mouse.
>* Lucky doesn't remember the number 3 before but now he does -- 'Oh! That's it! Three is what comes after two!" (maybe a joke that 4 is next but it seems shorter than 3 and that doesn't make sense but...) Or, alternatively, do I deserve a "that's the joke" gif for missing something here?

 * * *

"You're thinking of the number two," says the scientist with conviction.
"Yes again!" says the dog, now satisfied.
"But," objects the mouse, "Lucky only knows two numbers… what does that prove?"
>* Lucky just learned 3 earlier ... or he should have. So the mouse is being a bit mean here.

**Comment by dhakajack** [comment]
Agree. I came up with a minor patch to make it consistent:

How about we renumber? One: prepare the cure; two: get out of the installation; thr... rather, the number after two: find Lucky's family. Does that work for you?
