### ISSUE TITLE
Blue place description quibbles

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#23]
At the start,

"The blue place
A dark room.

You can see a small gray creature here."

If it's dark, how do you manage to see something small and gray, or know the room is blue? It seems like there needs to be some light source, since it is a dead end in a sealed off research laboratory. Maybe "It's so dark. Not totally dark, but enough to be scary." (?)

**Comment by dhakajack** [comment]
changed to 
say "A dimly lit room[one of] with some deep shadows[or][stopping]";
